# Minimal Dart CLI container
FROM dart

RUN mkdir /src
# COPY src /
# WORKDIR /src

# RUN dart pub get
# RUN dart compile exe /src/bin/euler.dart -o /euler

# Build minimal  image from AOT-compiled `/batman`
# FROM build
# COPY --from=build /batman /batman
# WORKDIR /
# RUN /batman install

# Run a base line and schedule scans.
# ENTRYPOINT ["/batman", "--quiet", "--no-colour", "cron", "--baseline", "30 22 * * * *"]

# remove the ENTRYPOINT and uncomment this line to enable interactive debugging.
# CMD ["bash"]
